# Generated by Django 3.2.5 on 2021-08-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210819_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='PostTag',
            new_name='ArticleCategory',
        ),
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='ArticleLevel',
        ),
        migrations.RenameModel(
            old_name='PostLevel',
            new_name='ArticleTag',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='article',
        ),
    ]
